#!/usr/bin/env bash
# https://asdf-vm.com/plugins/create.html#extension-commands-for-asdf-cli
# https://gut.readthedocs.io/en/v9.5.0/Command-Line.html
#set -o errexit
# set -o nounset
# set -o pipefail

HELP_TEXT="
usage: asdf cmd godot test [dir]

positional arguments:
dir : the directory to test.

options:
-h, --help    : show this help message and exit
"
GUT_LOC="$PWD/addons/gut"

[[ -d "$GUT_LOC" ]] || { echo "GUT was not found"; exit 1; }

function print-help () {
    # test args, if the last one is -h or --help
    # print help and exit
    case "${@: -1}" in
        *) if [[ "$#" -gt 0 ]]; then
               echo "args exist"
               return
           fi
           ;;
    esac
    echo -e "$HELP_TEXT"

    if [[ -d "GUTLOC" ]]; then
        godot --headless -d -s --path "$PWD" "$PWD/addons/gut/gut_cmdln.gd" -gh
    fi
    exit 0
}

print-help "$@"

godot_args=(
    --headless
    --script
    --path "$PWD"
)

gut_args=(
    "$PWD/addons/gut/gut_cmdln.gd"
    -gexit
    -gdir "${1:-__tests}"
)

# TODO: Parse Args

godot "${godot_args[@]}" "${gut_args[@]}"
